title: Yet Less Progress
show_downloads: true
zip_download: https://github.com/BreadBox64/YetLessProgress_Game/archive/main.zip
latest_download: https://github.com/BreadBox64/YetLessProgress_Game/releases/download/v0.1.0-alpha/0.1.0-alpha.windows64.zip
google_analytics: G-JZX6L6PWCN
theme: jekyll-theme-cayman
