title: Yet Less Progress
show_downloads: true
zip_download: https://github.com/BreadBox64/YetLessProgress_Game/archive/main.zip
latest_download: https://github.com/BreadBox64/YetLessProgress_Game/archive/main.zip
google_analytics: G-JZX6L6PWCN
theme: jekyll-theme-cayman